# Generated by Django 5.2.1 on 2025-05-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='carrying',
            new_name='hasTrash',
        ),
        migrations.AlterField(
            model_name='robot',
            name='x',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='robot',
            name='y',
            field=models.IntegerField(default=15),
        ),
    ]
